// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: RS485TempHumi

#ifndef _RS485TEMPHUMI_UI_H
#define _RS485TEMPHUMI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_none_png);    // assets/none.png
LV_IMG_DECLARE(ui_img_temperature_png);    // assets/temperature.png
LV_IMG_DECLARE(ui_img_humidity_png);    // assets/humidity.png
LV_IMG_DECLARE(ui_img_1042780322);    // assets/slide-clr.png
LV_IMG_DECLARE(ui_img_slide_knob_png);    // assets/slide_knob.png

// FONTS
LV_FONT_DECLARE(ui_font_gothic30);
LV_FONT_DECLARE(ui_font_gothic40);
LV_FONT_DECLARE(ui_font_gothic16);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
