// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: RS485TempHumi

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

extern void (*testBuzz)(uint8_t); 
extern void (*brightness)(uint8_t);
// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern void ui_event_tempgauge(lv_event_t * e);
extern lv_obj_t * ui_tempgauge;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern void ui_event_hunigauge(lv_event_t * e);
extern lv_obj_t * ui_hunigauge;
extern void ui_event_Label3(lv_event_t * e);
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern void btn_event_cb(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label5;
extern void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_TextArea1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

